// Generated by CoffeeScript 1.5.0
(function() {
  var gender, name, person, yell;

  name = "Skyler";

  person = true;

  console.log("Hello world");

  yell = function(a) {
    var age;
    age = a;
    name;
    return alert(age);
  };

  if (person === true && name !== "Skyler") {
    yell(25);
  }

  gender = "";

  if (gender == null) {
    gender = Male;
  }

}).call(this);
