// Generated by CoffeeScript 1.5.0
(function() {

  window.drawVVH = function(canvas, moveList) {
    var c, ctx, maxH, maxW, rmax, xlabel, xs, ys;
    console.log(moveList);
    c = document.getElementById(canvas);
    maxH = c.height;
    maxW = c.width;
    xs = 20;
    ys = 20;
    rmax = 20;
    ctx = c.getContext("2d");
    ctx.fillStyle = "black";
    ctx.fillRect(0, 0, maxW, maxH);
    xlabel = function() {
      var i, _results;
      ctx = c.getContext("2d");
      ctx.textBaseline = "middle";
      ctx.textAlign = "center";
      ctx.fillStyle = "white";
      ctx.fillText("D", canvas.width / 2, 10 * 2);
      i = 0;
      _results = [];
      while (i <= maxW) {
        if (i % rmax === 0) {
          ctx.fillText(i, (maxW / 2) - i, 20);
          ctx.fillText(i, (maxW / 2) + i, 20);
        }
        _results.push(i += xs);
      }
      return _results;
    };
    return xlabel();
  };

}).call(this);
