// Generated by CoffeeScript 1.5.0
(function() {

  window.drawVVH = function(canvas, moveList) {
    var xlabel, ylabel;
    console.log(moveList);
    Draw(the(Horizontal(Axis(Label))));
    xlabel = function() {
      var ctx, i, x, _results;
      ctx = canvas.getContext("2d");
      ctx.textBaseline = "middle";
      ctx.textAlign = "center";
      ctx.fillStyle = "red";
      i = void 0;
      x = void 0;
      ctx.fillText("D", canvas.width / 2, vvh.ts * 2);
      i = 0;
      _results = [];
      while (i <= rmax) {
        if (i % (5 * vvh.xs) === 0) {
          ctx.fillText(i, canvas.width / 2 + vvh.rs * (rmax + 1 - i), vvh.ts * 2);
          ctx.fillText(i, canvas.width / 2 - vvh.rs * (rmax + 1 - i), vvh.ts * 2);
        }
        _results.push(i++);
      }
      return _results;
    };
    xlabel();
    ylabel = function() {
      var ctx, i, y, _results;
      ctx = canvas.getContext("2d");
      ctx.textBaseline = "middle";
      ctx.textAlign = "center";
      ctx.fillStyle = vvh.line;
      i = void 0;
      y = void 0;
      i = 0;
      _results = [];
      while (i < (canvas.height - vvh.ts * 3) / vvh.ts) {
        if (i % vvh.ys === 0) {
          y = i;
          ctx.fillText(y, canvas.width / 2 - (rmax + 1) * vvh.rs - 10, vvh.ts * (i + 3));
          ctx.fillText(y, canvas.width / 2 + (rmax + 1) * vvh.rs + 10, vvh.ts * (i + 3));
        }
        _results.push(i++);
      }
      return _results;
    };
    return ylabel();
  };

}).call(this);
